[
    {
      "name": "Blood Bank",
      "description" : "BLOOD BANK The Blood Bank of United Hospital Limited is a Government licensed blood bank established in 2006.  Located in the ground floor of this hospital, it aims to provide patients with the safest possible blood, equivalent to any international standard. All donations received in the blood bank are voluntary non-remunerated. All necessary safety measures are taken for both the donors and the recipients including performing the mandatory screening tests for infectious diseases. This blood bank is enriched with one Consultant, one Specialist, four Senior House Officers, and thirteen Medical Lab Technologists.",
      "one": "Whole blood ",
      "two": "Red cell concentrate (PRBC)",
      "three": "Washed red cellsFresh",
      "four": "frozen plasma (FFP)",
      "five": "Pooled platelet concentrate",
      "six": " Apheresis platelet concentrate",
      "seven": "Cryoprecipitate",
      "eight": "Granulocyte  by apheresis.",
      "footer": "Committed to deliver high quality and safe blood products, our blood banking and transfusion services are available round the clock seven days a week. "
    },
    {
      "name": "CAFETERIA",
      "description" : "Guest Cafeteria of United Hospital is open 24 hours every day. The Cafeteria offers hygienic and delicious meal options, including vegetarian choices, local and continental cuisine, salads, snacks, grills, ice-creams, milk shake, and fresh juices to retain our patients & guests a healthy mind. Breakfast, Lunch and Dinner including all the food items are made by In-house.",
      "one": "Whole blood ",
      "two": "Red cell concentrate (PRBC)",
      "three": "Washed red cellsFresh",
      "four": "frozen plasma (FFP)",
      "five": "Pooled platelet concentrate",
      "six": " Apheresis platelet concentrate",
      "seven": "Cryoprecipitate",
      "eight": "Granulocyte  by apheresis.",
      "footer": "Committed to deliver high quality and safe blood products, our blood banking and transfusion services are available round the clock seven days a week. "
    },
    {
      "name": "CHEMOTHERAPY",
      "description" : "CHEMOTHERAPY Chemotherapy UnitOur exclusive Chemotherapy Unit provides the most updated cancer management as per international guidelines.What is chemotherapy?Chemotherapy (also called chemo) is a type of cancer treatment that uses drugs to destroy cancer cells.How does chemotherapy work?Chemotherapy works by stopping or slowing the growth of cancer cells, which grow and divide quickly. But it can also harm healthy cells that divide quickly, such as those that line your mouth and intestines or cause your hair to grow. Damage to healthy cells may cause side effects. Often, side effects get better or go away after chemotherapy is over.",
      "one": "Whole blood ",
      "two": "Red cell concentrate (PRBC)",
      "three": "Washed red cellsFresh",
      "four": "frozen plasma (FFP)",
      "five": "Pooled platelet concentrate",
      "six": " Apheresis platelet concentrate",
      "seven": "Cryoprecipitate",
      "eight": "Granulocyte  by apheresis.",
      "footer": "Committed to deliver high quality and safe blood products, our blood banking and transfusion services are available round the clock seven days a week. "
    },
    {
      "name": "DAY CARE",
      "description" : "The Day Care Unit is a unique wing of United Hospital to help patients with specific need-based treatment in an out-patient basis. Patients in Day Care are those who undergo procedures not requiring overnight nursing care or stay in the hospital. Patients can have the procedure and then rest and be monitored in Day Care Unit for a few hours after the procedure. Afterwards, they can return home that same day. All beds in Day Care Unit are equipped with life supports.",
      "one": "Whole blood ",
      "two": "Red cell concentrate (PRBC) ,Day Care (under Medical Oncology Department) United Hospital Chemotherapy Day Care Unit is dedicated to providing chemotherapy services for the management of cancer patients. We have a standard, fully equipped 10-bedded day-care facility and a large indoor facility for a wide range of treatments for patients requiring chemotherapy and conservative medical management. Medical oncologists at Apollo often utilize chemotherapy, which uses systemic treatment in the form of intravenous injections of anticancer drugs or, less commonly, oral medications to kill cancer cells. Chemotherapy Day Care is located in Ground Floor of the hospital.To know more about our chemotherapyandcancer management services, Contact: (02)-8836000 Ext: 8045 & 8929. Cell No. 0191 400 1382",
      "three": "Washed red cellsFresh",
      "four": "frozen plasma (FFP)",
      "five": "Pooled platelet concentrate",
      "six": " Apheresis platelet concentrate",
      "seven": "Cryoprecipitate",
      "eight": "Granulocyte  by apheresis.",
      "footer": "Committed to deliver high quality and safe blood products, our blood banking and transfusion services are available round the clock seven days a week. "
    },
        {
      "name":"DIABETES CENTER",
      "description" : "Are you one of the millions of Bangladeshi with Diabetes? If so, there is so much you can learn and do to manage your Diabetes, prevent complications and enjoy quality of life. The United Diabetes Center can help you every step of the way.",
      "one": "Whole blood ",
      "two": "Red cell concentrate (PRBC)",
      "three": "Washed red cellsFresh",
      "four": "frozen plasma (FFP)",
      "five": "Pooled platelet concentrate",
      "six": " Apheresis platelet concentrate",
      "seven": "Cryoprecipitate",
      "eight": "Granulocyte  by apheresis.",
      "footer": "Committed to deliver high quality and safe blood products, our blood banking and transfusion services are available round the clock seven days a week. "
    },
    
        {
      "name":"EMERGENCY",
      "description" : "A Center of Excellence in Emergency Medicine of BangladeshThe emergency department provides service 24 hours a day and 7 days a week. ICU ambulance service is also available for both critical and non-critical patient transfers in Dhaka and surrounding areas. In case of any emergency, use our Emergency/ Ambulance service line at +880 191 400 1234. Our ambulance will reach you anywhere in Dhaka to provide you with the best medical care in Bangladesh.",
      "one": "United Hospital Emergency is one of the largest, modern and well equipped Emergency Department in this territory providing services 24X7",
      "two": "It is a Reception Management area for all emergency cases",
      "three": "Working 24x7 and ready to provide services to male-female of all age groups",
      "four": "Any (patient) victim with serious medical or surgical condition in need of an immediate management",
      "five": "We have 24/7 Ambulance service with dedicated BLS &ALS medical team ( EMT)",
      "six": "Registration of patient and issuing MRN card for all emergency patient seeking for care",
      "seven": "Help in completing patients personal data",
      "eight": "ED admission in respective department",
      "footer": "Committed to deliver high quality and safe blood products, our blood banking and transfusion services are available round the clock seven days a week. "
    },
        {
      "name":"Screening at doorstep: A smart step for your health",
      "description" : "The prospect of spending hours in a queue at the diagnostic lab or the hospital deters many or at least prompts them to defer stepping out for diagnostic tests. For many people, the idea of spending hours in a lab or hospital may sound demotivating. Many people also avoid going for preventive screenings and lab tests as they dread battling city traffic. In certain cases, travel-related stress can increase the risk of infection and delay recovery. At COVID times, many also don’t want to visit labs to avoid spread or contamination.Patients who are aged ones who face problems in travelling and prefer the tests to be conducted in the comfort of their home or morbid patients who cannot move or go to the lab to perform a test or when it is not feasible for them to travel to the lab, prefer to get the blood sample collection at home. Doorstep sample collection facility reduces the anxiety and it is less stressful for the patient as visiting the lab. Moreover there are people who are immunocompromised, people suffering from diseases like cancer which cause less immunity in their body; these people are very vulnerable and any disease can get easily transmitted to their body. Due to such conditions, it is always good for them to have the facility of blood collection from home, especially when people do seek for such facility from a trusted centre, a lab which they can rely on.",
      "one": "Whole blood ",
      "two": "Red cell concentrate (PRBC)",
      "three": "Washed red cellsFresh",
      "four": "frozen plasma (FFP)",
      "five": "Pooled platelet concentrate",
      "six": " Apheresis platelet concentrate",
      "seven": "Cryoprecipitate",
      "eight": "Granulocyte  by apheresis.",
      "footer": "Committed to deliver high quality and safe blood products, our blood banking and transfusion services are available round the clock seven days a week. "
    },
        {
      "name":"HOME SAMPLE COLLECTION SERVICE",
      "description" : "Home Sample Collection Service in Dhaka City (COVID & Non-COVID)Our objective is to deliver high quality special healthcare service to our patients who are unable to come to the hospital to give blood/urine/stool samples for treatment or routine health checkup purpose.Gulshan, Niketon, Banani, Banani DOHS, Baridhara, Baridhara DOHS, Bashundhara, Badda, Mohakhali, Cantonment, Uttara, Abdullahpur, Dhanmondi, Lalmatia, Mohammadpur, Farmgate, Pallabi, Mirpur, Kafrul, Tejgaon, Maghbazar, Banasree, Rampura, Malibagh, Kakrail, Ramna, Arambagh, Motijheel, Khilgaon and ShobujbaghOur trained & skilled phlebotomists are collecting samples from your location.Patient satisfaction is our priority.For COVID/Non-COVID sample collection 10666 or 02 22 22 62 466",
      "one": "Whole blood ",
      "two": "Red cell concentrate (PRBC)",
      "three": "Washed red cellsFresh",
      "four": "frozen plasma (FFP)",
      "five": "Pooled platelet concentrate",
      "six": " Apheresis platelet concentrate",
      "seven": "Cryoprecipitate",
      "eight": "Granulocyte  by apheresis.",
      "footer": "Committed to deliver high quality and safe blood products, our blood banking and transfusion services are available round the clock seven days a week. "
    },
        {
      "name":"MEDICAL RECORDS",
      "description" : "Medical Records is systemic documentation of a patient’s medical history and care. It contains necessary data in sequence in order to justify the diagnosis, treatment and outcome correctly and effectively.We intend to maintain Electronic Health Records (EHR) and hard copy format in parallel with Computerized Provider Order Entry.Medical Records Department is responsible for maintaining, storing and smooth flow of patient medical records in a standardize and professional manner in order to protect patient confidentiality to promote authentic patient care.Birth certificate/duplicate birth certificate, duplicate/amended death certificate, fitness certificate/medical certificate, duplicate /Xerox copy of investigations (radiological and pathological), prescriptions for OPD patient and for IPD patient discharge summary are generally provided from medical records department as well as all kinds of insurance claim forms are also processed by medical records department as per the protocol of UHL. Some charges to be paid at accounts department for different kind of documents, these are•   Filling of insurance claims form BDT 1000•   Medical Certificate or Fitness Certificate BDT 2000•   Duplicate Birth Certificate BDT 500•   Duplicate/amended death certificate BDT 1500•   Duplicate copy of investigation/Xerox copy of investigations with OPD Prescription (Radiological and Pathological) BDT 500•   IPD (Inpatient Documents-Discharge Summary and investigations BDT 500•  Name amendment BDT 200•  Case summary charge-BDT 2000 taka",
      "one": "Whole blood ",
      "two": "Red cell concentrate (PRBC)",
      "three": "Washed red cellsFresh",
      "four": "frozen plasma (FFP)",
      "five": "Pooled platelet concentrate",
      "six": " Apheresis platelet concentrate",
      "seven": "Cryoprecipitate",
      "eight": "Granulocyte  by apheresis.",
      "footer": "Committed to deliver high quality and safe blood products, our blood banking and transfusion services are available round the clock seven days a week. "
    },
        {
      "name":"MORTUARY",
      "description" : "Mortuary Freezer of United Hospital is of Italian origin and is made of stainless steel. It has two separate cold chambers and can accommodate two dead bodies at a time at two different chambers. Working temperature of mortuary is 00  c and temperature range can be varied from -50 c to +50 c. Temperature of cold chamber is being maintained and checked by Biomedical Department in coordination with Duty Manager.Since we have two chambers, so the preference is given to In patients. However, if the space is available then only out door bodies are also allowed to be preserved for short duration.In addition to the mortuary, we have a proper place for washing of dead bodies prior to burial. Hospital authority always take this responsibility as their morale duty to ensure proper respect and handling of the dead bodies preserved in the hospital mortuary",
      "one": "Whole blood ",
      "two": "Red cell concentrate (PRBC)",
      "three": "Washed red cellsFresh",
      "four": "frozen plasma (FFP)",
      "five": "Pooled platelet concentrate",
      "six": " Apheresis platelet concentrate",
      "seven": "Cryoprecipitate",
      "eight": "Granulocyte  by apheresis.",
      "footer": "Committed to deliver high quality and safe blood products, our blood banking and transfusion services are available round the clock seven days a week. "
    },
        {
      "name":"MULTIDISCIPLINARY TEAM ASSESSMENT (MDTA) CARE",
      "description" : "Multidisciplinary Team care is an integrated team assessment of United Hospital Limited will provide the most comprehensive care possible at the right place and time for each patient.",
      "one": "Team approach where care experts and related healthcare professionals deal with not only the treatment plans and delivery of care but also the psychosocial aspects of care",
      "two": "Regular communication with team members.",
      "three": "Access to a full range of therapeutic options",
      "four": "Patient will be included in their care discussions and management and receive timely and appropriate information from healthcare professionals",
      "five": "Improved treatment and quality care.",
      "six": " Apheresis platelet concentrate",
      "seven": "Better access to health information",
      "eight": "Likelihood of receiving care involving psychosocial support.",
      "footer": "treamlined treatment pathways and reduction in duplication of services. "
    },
        {
      "name":"THE PHARMACY DEPARTMENT ",
      "description" : "This has placed a leading role in implementing advanced clinical pharmacist patient care services in Personal Health care where pharmacists work collaboratively with nurses and physicians directly on patient care areas to review medication orders and manage drug therapy.The Pharmacy Department of United Hospital provides a comprehensive range of pharmaceutical services to all patients. Its objective is to provide patient-focused pharmaceutical care in order to achieve definite outcomes that improve patients’ quality of life. The pharmacy department consists of a team of qualified, ....",
      "one": "Team approach where care experts and related healthcare professionals deal with not only the treatment plans and delivery of care but also the psychosocial aspects of care",
      "two": "Regular communication with team members.",
      "three": "Access to a full range of therapeutic options",
      "four": "Patient will be included in their care discussions and management and receive timely and appropriate information from healthcare professionals",
      "five": "Improved treatment and quality care.",
      "six": " Apheresis platelet concentrate",
      "seven": "Better access to health information",
      "eight": "Likelihood of receiving care involving psychosocial support.",
      "footer": "treamlined treatment pathways and reduction in duplication of services. "
    },
        {
      "name":"PHYSIOTHERAPY",
      "description" : "Our body is a complex combination of bones, muscles, tissues, blood vessels, organs, etc. These take a beating with time and age owing to factors like injuries, diseases, or environmental changes. Thus, a regular visit to a physiotherapist is recommended to restore the body’s smooth functioning and healthy lifestyle. You will find the one of best physiotherapy in Dhaka at United Hospital. Physiotherapy service at United Hospital, Dhaka offers comprehensive treatment by identifying the causes of movement and functioning defects and aiming to maximize the quality of life through application of vast knowledge and advanced technology by our specialists. The treatment process involves one on one interaction between the patient and physical therapist, other health professionals, families, caregivers, etc. in order to understand the challenges faced by the patient. Physiotherapy service at United Hospital Dhaka then drafts out a rehabilitation plan containing treatment to be followed and care to be given after the procedure is complete.Physical medicine and rehabilitation also known as physiatry or rehabilitation medicine is a medical specialty that helps people regain bodily functions they lost due to medical conditions or injury. Rehabilitation can help many bodily functions, including bowel and bladder problems, chewing and swallowing, problems thinking or reasoning, movement or mobility, speech, and language.",
      "one": "Neck Pain & Back Pain (involving Spine)",
      "two": "Frozen Shoulder",
      "three": "Rheumatoid Arthritis      ",
      "four": "Ankylosing Spondylitis",
      "five": "Stroke",
      "six": " Head Injury",
      "seven": "Better access to health information",
      "eight": "Guillain Barre Syndrome.",
      "footer": "Motor Neuron Diseases. "
    },
        {
      "name":"REPORT DELIVERY",
      "description" : "Report Delivery Service is located at the Ground Floor of the hospital’s lobby, providing 24 hours Service to deliver all kinds of investigation reports.",
      "one": "Neck Pain & Back Pain (involving Spine)",
      "two": "Frozen Shoulder",
      "three": "Rheumatoid Arthritis      ",
      "four": "Ankylosing Spondylitis",
      "five": "Stroke",
      "six": " Head Injury",
      "seven": "Better access to health information",
      "eight": "Guillain Barre Syndrome.",
      "footer": "Motor Neuron Diseases. "
    },
        {
      "name":"STROKE CENTRE",
      "description" : "STROKE is a serious, life-threatening medical condition that occurs when the blood supply to part of the brain is cut off.Minutes can make a difference between life and death, the difference between brain cells that are saved and brain cells that are damaged forever, between recovery and lifelong disability.The more time passes before a stroke patient receives treatment, the worst the outcome. So if the stroke is treated immediately, brain damage will be minimized.",
      "one": "Neck Pain & Back Pain (involving Spine)",
      "two": "Frozen Shoulder",
      "three": "Rheumatoid Arthritis      ",
      "four": "Ankylosing Spondylitis",
      "five": "Stroke",
      "six": " Head Injury",
      "seven": "Better access to health information",
      "eight": "Guillain Barre Syndrome.",
      "footer": "Motor Neuron Diseases. "
    },
        {
      "name":"Dermatology",
      "description" : "The department of Dermatology provides comprehensive diagnosis and treatment for all skin, hair and nail related diseases. The Department is committed to the highest level of patient care by addressing the patient’s dermatological needs and offering them the best of treatments. We use a multidisciplinary team approach to provide treatment for people of all ages.Apollo Hospitals offers advanced and unmatched dermatological care with modern technology in a soothing and pleasant environment. Our dermatologists are known to treat manifold and complex dermatological diseases with utmost precision and skill. We also believe that prevention is better than cure. Hence, we educate our patients regarding various dermatological diseases and on practicing a healthy lifestyle.      ",
      "one": "Neck Pain & Back Pain (involving Spine)",
      "two": "Frozen Shoulder",
      "three": "Rheumatoid Arthritis      ",
      "four": "Ankylosing Spondylitis",
      "five": "Stroke",
      "six": " Head Injury",
      "seven": "Better access to health information",
      "eight": "Guillain Barre Syndrome.",
      "footer": "Motor Neuron Diseases. "
    },
        {
      "name":"pregnancy",
      "description" : "An unborn baby spends around 38 weeks in the womb, but the average length of pregnancy (gestation) is counted as 40 weeks.This is because pregnancy is counted from the first day of the woman’s last period, not the date of conception, which generally occurs 2 weeks later. If you are experiencing any of these symptoms and think you may be pregnant, it is a good idea to take a pregnancy test.If you didn't plan to become pregnant, it is important to have a pregnancy test as soon as you can. The sooner a pregnancy is confirmed, the sooner you can receive care, and the more options will be available to you.During the first trimester, miscarriage is common. Around 1 in 4 pregnancies end in miscarriage. Most spontaneous miscarriages (75 to 80 per cent) occur in the first 12 weeks. Many miscarriages are unreported or go unrecognised because they occur very early in pregnancy.",
      "one": "Neck Pain & Back Pain (involving Spine)",
      "two": "Frozen Shoulder",
      "three": "Rheumatoid Arthritis      ",
      "four": "Ankylosing Spondylitis",
      "five": "Stroke",
      "six": " Head Injury",
      "seven": "Better access to health information",
      "eight": "Guillain Barre Syndrome.",
      "footer": "Motor Neuron Diseases. "
    },
        {
      "name":"Care for sick children",
      "description" : "Children who are too sick to be managed at first-level health facilities may be referred and managed in local hospitals. These children are the most severely ill and at the greatest risk of dying. Improvements in triage, diagnosis, treatment, monitoring, and follow up care can greatly improve the chances of survival.Improving the quality of care at this level requires ensuring the availability quality medicines and other supplies, enhancing health worker compliance with evidence-based clinical interventions and practices, correcting inadequate or unhygienic infrastructure, developing competencies, motivating staff, and supporting better documentation and use of information. WHO focuses on developing evidence-based clinical guidelines and care support tools, strategies for improving quality of care, and training courses for health workers",
      "one": "Neck Pain & Back Pain (involving Spine)",
      "two": "Frozen Shoulder",
      "three": "Rheumatoid Arthritis      ",
      "four": "Ankylosing Spondylitis",
      "five": "Stroke",
      "six": " Head Injury",
      "seven": "Better access to health information",
      "eight": "Guillain Barre Syndrome.",
      "footer": "Motor Neuron Diseases. "
    },
   ]